//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ahkam
    {
        public int id { get; set; }
        public int userpersonal { get; set; }
        public string type { get; set; }
        public string date { get; set; }
        public string type1 { get; set; }
        public string type2 { get; set; }
        public string type3 { get; set; }
        public string type4 { get; set; }
        public string type5 { get; set; }
    }
}
