//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int Devices_ID { get; set; }
        public Nullable<int> Devices_Users_ID { get; set; }
        public string Devices_Model { get; set; }
        public string Devices_Token { get; set; }
        public string Devices_DeviceID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
