//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.GroupMessages = new HashSet<GroupMessages>();
            this.GroupsMember = new HashSet<GroupsMember>();
        }
    
        public int Groups_ID { get; set; }
        public Nullable<int> Groups_Creator_ID { get; set; }
        public string Groups_Title { get; set; }
        public string Groups_About { get; set; }
        public string Groups_Avatar { get; set; }
        public string Groups_Insert_Date { get; set; }
        public Nullable<int> Groups_Type { get; set; }
        public string Groups_Username { get; set; }
        public Nullable<bool> Groups_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMessages> GroupMessages { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupsMember> GroupsMember { get; set; }
    }
}
