//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupMessages()
        {
            this.GroupMessages1 = new HashSet<GroupMessages>();
            this.GroupMessages11 = new HashSet<GroupMessages>();
            this.MessageSeens = new HashSet<MessageSeens>();
        }
    
        public int GroupMessages_ID { get; set; }
        public string GroupMessages_Text { get; set; }
        public string GroupMessages_Insert_Date { get; set; }
        public int GroupMessages_Sender_ID { get; set; }
        public int GroupMessages_Group_ID { get; set; }
        public Nullable<int> GroupMessages_Reply_Parent { get; set; }
        public string GroupMessages_File { get; set; }
        public Nullable<bool> GroupMessages_Seen_Status { get; set; }
        public Nullable<int> GroupMessages_Forward_ID { get; set; }
        public bool GroupMessages_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMessages> GroupMessages1 { get; set; }
        public virtual GroupMessages GroupMessages2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMessages> GroupMessages11 { get; set; }
        public virtual GroupMessages GroupMessages3 { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageSeens> MessageSeens { get; set; }
    }
}
