//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsMember
    {
        public int GroupsMember_ID { get; set; }
        public int GroupsMember_Group_ID { get; set; }
        public int GroupsMember_Member_ID { get; set; }
        public bool GroupsMember_Admin_Status { get; set; }
        public bool GroupsMember_Blocked_Status { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
    }
}
