//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageSeens
    {
        public int MessageSeens_ID { get; set; }
        public int MessageSeens_Users_ID { get; set; }
        public int MessageSeens_Message_ID { get; set; }
        public string MessageSeens_View_Date { get; set; }
        public bool MessageSeens_Liked_Status { get; set; }
    
        public virtual GroupMessages GroupMessages { get; set; }
        public virtual Users Users { get; set; }
    }
}
