//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvupdate
    {
        public int id_update { get; set; }
        public string username_l { get; set; }
        public string last_update { get; set; }
        public string xx1 { get; set; }
        public string xx2 { get; set; }
        public string xx3 { get; set; }
        public string xx4 { get; set; }
        public string xx5 { get; set; }
        public string xx6 { get; set; }
    }
}
