//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDATA
    {
        public int id_data { get; set; }
        public Nullable<int> d_personalcode { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string codemelli { get; set; }
        public string shenasname { get; set; }
        public string tell { get; set; }
        public string mobile { get; set; }
        public string madrak { get; set; }
        public string reshtetahsili { get; set; }
        public string gerayesh { get; set; }
        public string tozihat { get; set; }
        public string noegarardad { get; set; }
        public string mahalesodor { get; set; }
        public string saletavalode { get; set; }
        public string mahetavalode { get; set; }
        public string rozetavalod { get; set; }
        public string address { get; set; }
        public string jensiyat { get; set; }
        public string dadname { get; set; }
        public string shomarehesab { get; set; }
        public string shaba { get; set; }
        public string bank { get; set; }
        public string vahed { get; set; }
        public string shomarebime { get; set; }
        public string tarikheestekhdam { get; set; }
        public string shobe { get; set; }
        public string zirshobe { get; set; }
        public string sath { get; set; }
        public string safesetade { get; set; }
        public string d1 { get; set; }
        public string d2 { get; set; }
        public string d3 { get; set; }
        public string d4 { get; set; }
        public string d5 { get; set; }
        public string d6 { get; set; }
        public string d7 { get; set; }
        public string d8 { get; set; }
        public string d9 { get; set; }
        public string d10 { get; set; }
        public string d11 { get; set; }
        public string d12 { get; set; }
        public string d13 { get; set; }
        public string d14 { get; set; }
        public string d15 { get; set; }
    }
}
