//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSERS
    {
        public int suserid { get; set; }
        public Nullable<int> personalcode { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string phone { get; set; }
        public Nullable<int> code { get; set; }
        public string pic { get; set; }
        public string x1 { get; set; }
        public string x2 { get; set; }
        public string x3 { get; set; }
        public string x4 { get; set; }
        public string x5 { get; set; }
        public string Devise_Model { get; set; }
        public string Devise_name { get; set; }
        public string Devise_ID { get; set; }
        public string Divise_Token { get; set; }
        public string lastupdate { get; set; }
    }
}
