//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiket
    {
        public int id_tiket { get; set; }
        public string tdate { get; set; }
        public string ttime { get; set; }
        public string tcategori { get; set; }
        public string ttitle { get; set; }
        public string tdescription { get; set; }
        public string tpgcode { get; set; }
        public string tgname { get; set; }
        public string btell { get; set; }
        public string tvisitor { get; set; }
        public string tresponse { get; set; }
        public string trdate { get; set; }
        public string trtime { get; set; }
        public string truser { get; set; }
        public string tstatuse { get; set; }
        public string x1 { get; set; }
        public string x2 { get; set; }
        public string x3 { get; set; }
        public string x4 { get; set; }
    }
}
